# Generated by Django 6.0.1 on 2026-01-22 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lead_interaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('interactions', models.TextField(blank=True, help_text='Notes, calls, emails, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lead',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='lead',
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='first_name',
            field=models.CharField(default='unknown@example.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='interactions',
            field=models.TextField(blank=True, help_text='Notes, calls, emails, etc.', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_name',
            field=models.CharField(default='unknown@example.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='client',
            field=models.OneToOneField(blank=True, help_text='If the lead is converted, link to a client', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Interaction',
        ),
    ]
