# Generated by Django 6.0.1 on 2026-01-22 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_lead_status_interaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='interactions',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='interactions',
        ),
        migrations.AlterField(
            model_name='lead',
            name='client',
            field=models.OneToOneField(blank=True, help_text='Linked client after conversion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client'),
        ),
    ]
