# Generated by Django 6.0.1 on 2026-01-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_client_address_client_city_client_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='service_1_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='service_1_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='service_2_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='service_2_selected',
            field=models.BooleanField(default=False),
        ),
    ]
