# Generated by Django 6.0.1 on 2026-01-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lead_service_1_info_lead_service_1_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='service_1_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='service_1_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='service_2_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='service_2_selected',
            field=models.BooleanField(default=False),
        ),
    ]
