# Generated by Django 6.0.1 on 2026-01-27 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_client_service_1_info_client_service_1_selected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesMade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('ssn_last4', models.CharField(blank=True, max_length=4, null=True, verbose_name='SSN (/Last 4)')),
                ('qualification_notes', models.TextField(blank=True, null=True)),
                ('service_1_selected', models.BooleanField(default=False)),
                ('service_1_info', models.TextField(blank=True, null=True)),
                ('service_2_selected', models.BooleanField(default=False)),
                ('service_2_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sales Made',
                'verbose_name_plural': 'Sales Made',
            },
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='lead',
        ),
        migrations.AddField(
            model_name='client',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('converted', 'Converted'), ('archived', 'Archived')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='ssn_last4',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='SSN (/Last 4)'),
        ),
        migrations.AddField(
            model_name='client',
            name='sales_made',
            field=models.OneToOneField(blank=True, help_text='Linked Sales Made client after conversion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.salesmade'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='sales_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_interactions', to='core.salesmade'),
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
