# Generated by Django 6.0.1 on 2026-01-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_salesmade_remove_interaction_lead_client_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ssn_last4',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='SSN (/Last 4)'),
        ),
        migrations.AlterField(
            model_name='salesmade',
            name='ssn_last4',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='SSN (/Last 4)'),
        ),
    ]
