# Generated by Django 6.0.1 on 2026-01-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_client_ssn_last4_alter_salesmade_ssn_last4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='service_1_info',
            new_name='service_description',
        ),
        migrations.RenameField(
            model_name='salesmade',
            old_name='service_1_info',
            new_name='service_description',
        ),
        migrations.RemoveField(
            model_name='client',
            name='service_1_selected',
        ),
        migrations.RemoveField(
            model_name='client',
            name='service_2_info',
        ),
        migrations.RemoveField(
            model_name='client',
            name='service_2_selected',
        ),
        migrations.RemoveField(
            model_name='salesmade',
            name='service_1_selected',
        ),
        migrations.RemoveField(
            model_name='salesmade',
            name='service_2_info',
        ),
        migrations.RemoveField(
            model_name='salesmade',
            name='service_2_selected',
        ),
        migrations.AddField(
            model_name='client',
            name='card_expiration',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='card_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesmade',
            name='card_expiration',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='salesmade',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='salesmade',
            name='card_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesmade',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesmade',
            name='payment_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
