# Generated by Django 6.0.1 on 2026-01-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_service_1_info_client_service_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='card_expiration',
        ),
        migrations.RemoveField(
            model_name='client',
            name='card_last4',
        ),
        migrations.RemoveField(
            model_name='client',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='client',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='service_description',
        ),
        migrations.RemoveField(
            model_name='salesmade',
            name='card_expiration',
        ),
        migrations.RemoveField(
            model_name='salesmade',
            name='card_last4',
        ),
        migrations.RemoveField(
            model_name='salesmade',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='salesmade',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='salesmade',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='salesmade',
            name='service_description',
        ),
        migrations.AddField(
            model_name='client',
            name='service_1_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='service_1_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='service_2_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='service_2_selected',
            field=models.BooleanField(default=False),
        ),
    ]
