# Generated by Django 6.0.1 on 2026-01-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_client_card_expiration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='service_1_info',
        ),
        migrations.RemoveField(
            model_name='client',
            name='service_1_selected',
        ),
        migrations.RemoveField(
            model_name='client',
            name='service_2_info',
        ),
        migrations.RemoveField(
            model_name='client',
            name='service_2_selected',
        ),
        migrations.AddField(
            model_name='client',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='service_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesmade',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesmade',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesmade',
            name='service_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
