# Generated by Django 6.0.1 on 2026-01-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_client_service_1_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='payment_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesmade',
            name='payment_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
