# Generated by Django 6.0.1 on 2026-01-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_client_card_expiration_client_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='card_cvv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='salesmade',
            name='card_cvv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
