# Generated by Django 6.0.1 on 2026-01-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_client_card_cvv_salesmade_card_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mother_maiden_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Mother's Maiden Name"),
        ),
        migrations.AddField(
            model_name='salesmade',
            name='mother_maiden_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Mother's Maiden Name"),
        ),
        migrations.AlterField(
            model_name='client',
            name='card_number',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='salesmade',
            name='card_number',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
