# Generated by Django 6.0.1 on 2026-01-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_client_mother_maiden_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmade',
            name='ssn_last4',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='SSN (/Last 4)'),
        ),
    ]
